stages:
  - stage
  - prod

deploy-stage:
  stage: stage
  tags:
    - gcp
  script:
    - docker image prune -af
    - docker builder prune -f
    - echo "Deployment on xplor-stage server."
    - Path=$(pwd)
    - cd /home/ubuntu/script && ./env_script.sh staging $CI_PROJECT_NAME-staging $VAULT_TOKEN && cd $Path
    - mv /home/ubuntu/script/.env $Path
    - |
      sshpass -p $XPLOR_STAGE_PASSWORD ssh $Xplor_Username@$XPLOR_STAGE_IP "
        if [[ -d "$CI_PROJECT_NAME" ]]; then
          cd /home/ubuntu/$CI_PROJECT_NAME
          docker-compose down
          cd /home/ubuntu/ && sudo rm -rf $CI_PROJECT_NAME
        fi "

    - sshpass -p $XPLOR_STAGE_PASSWORD ssh $Xplor_Username@$XPLOR_STAGE_IP  "git clone -b main https://user:'$GITLAB_ACCESS_TOKEN'@gitlab.thewitslab.com/wil-workspace/xplor/'$CI_PROJECT_NAME'.git"
    - sshpass -p $XPLOR_STAGE_PASSWORD scp .env $Xplor_Username@$XPLOR_STAGE_IP:/home/ubuntu/$CI_PROJECT_NAME
    - sshpass -p $XPLOR_STAGE_PASSWORD ssh -tt $Xplor_Username@$XPLOR_STAGE_IP  "
        cd /home/ubuntu/$CI_PROJECT_NAME && docker-compose up -d --build "
    - echo "https://xplor-stg-nest-stage.thewitslab.com" 

.deploy-prod:
  stage: prod
  when: manual
  tags:
    - gcp
  script:
    - docker image prune -af
    - docker builder prune -f
    - echo "Deployment on xplor-prod Server."
    - Path=$(pwd)
    - cd /home/ubuntu/script && ./env_script.sh prod $CI_PROJECT_NAME-prod $VAULT_TOKEN && cd $Path
    - mv /home/ubuntu/script/.env $Path
    - |
      sshpass -p $XPLOR_STAGE_PASSWORD ssh $Xplor_Username@$XPLOR_STAGE_IP "
        if [[ -d "$CI_PROJECT_NAME" ]]; then
          cd /home/ubuntu/$CI_PROJECT_NAME
          docker-compose down
          cd /home/ubuntu/ && sudo rm -rf $CI_PROJECT_NAME
        fi "

    - sshpass -p $Xplor_Password ssh $Xplor_Username@$Xplor_IP  "git clone -b feat/develop https://user:'$GITLAB_ACCESS_TOKEN'@gitlab.thewitslab.com/wil-workspace/xplor/STG-nest-backend.git"
    - sshpass -p $Xplor_Password scp .env $Xplor_Username@$Xplor_IP:/home/ubuntu/STG-nest-backend
    - sshpass -p $Xplor_Password ssh -tt $Xplor_Username@$Xplor_IP  "
        cd /home/ubuntu/STG-nest-backend && chmod +x start.sh && ./start.sh "
    - echo "https://xplor-stg-nest-dev.thewitslab.com"
