version: "3"
services:
  onboarding_service:
    container_name: xplor-onboarding-stg-service
    build: ./onboarding
    # ports:
    #   - 1105:3000
    restart: always
    networks:
      - xplor-network
    environment:
      - GRAFANA_SERVICE_URL=${GRAFANA_SERVICE_URL}
      - MONGODB_URL=${MONGODB_URL}

  nginx:
    image: nginx:alpine
    container_name: bharat-portal-nginx-container
    restart: always
    ports:
      - "1105:8080"
    depends_on:
      - onboarding_service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log:/etc/nginx/log/
      - ./api_json_errors.conf:/etc/nginx/api_json_errors.conf
    networks:
      - xplor-network

networks:
  xplor-network:
    external: true
