version: "3"

services:
  onboarding_service:
    logging:
      driver: "file-log-driver"
      options:
        fpath: "/docker/onboarding_service.log"
    container_name: xplor-onboarding-stg-service
    build: ./onboarding
    # ports:
    #   - 5006:5006
    restart: always
    networks:
      - xplor-network
    environment:
      - GRAFANA_SERVICE_URL=${GRAFANA_SERVICE_URL}
      - MONGODB_URL=${MONGODB_URL}
      - ONBOARDING_LAYER_PORT=${ONBOARDING_LAYER_PORT}

  app_service:
    logging:
      driver: "file-log-driver"
      options:
        fpath: "/docker/app_service.log"
    container_name: xplor-app-stg-service
    build: ./app-layer
    # ports:
    #   - 1105:3000
    restart: always
    # depends_on:
    #   - kafka
    networks:
      - xplor-network
    environment:
      - GRAFANA_SERVICE_URL=${GRAFANA_SERVICE_URL}
      - MONGODB_URL=${MONGODB_URL}
      - NODE_Env=${NODE_ENV}
      - APP_LAYER_PORT=${APP_LAYER_PORT}
      - PROTOCOL_DATABASE_URL=${PROTOCOL_DATABASE_URL}
      - PROTOCOL_SERVICE_URL=${PROTOCOL_SERVICE_URL}
      - APP_SERVICE_URL=${APP_SERVICE_URL}
      - CORE_SERVICE_URL=${CORE_SERVICE_URL}
      - IS_NETWORK_MOCK=${IS_NETWORK_MOCK}

  protocol_service:
    logging:
      driver: "file-log-driver"
      options:
        fpath: "/docker/protocol_service.log"
    container_name: xplor-protocol-stg-service
    build: ./protocol-layer
    # ports:
    #   - 5005:5005
    restart: always
    networks:
      - xplor-network
    environment:
      - GRAFANA_SERVICE_URL=${GRAFANA_SERVICE_URL}
      - MONGODB_URL=${MONGODB_URL}
      - PROTOCOL_APP_PORT=${PROTOCOL_APP_PORT}
      - NODE_ENV=${NODE_ENV}
      - PROTOCOL_DATABASE_URL=${PROTOCOL_DATABASE_URL}
      - APP_SERVICE_URL=${APP_SERVICE_URL}
      - ONDC_PRIVATE_KEY=${ONDC_PRIVATE_KEY}
      - ONDC_SUBSCRIBER_ID=${ONDC_SUBSCRIBER_ID}
      - ONDC_SUBSCRIBER_UNIQUE_KEY_ID=${ONDC_SUBSCRIBER_UNIQUE_KEY_ID}
      - IS_NETWORK_MOCK=${IS_NETWORK_MOCK}
      - BELEM_PRIVATE_KEY=${BELEM_PRIVATE_KEY}
      - BELEM_PUBLIC_KEY=${BELEM_PUBLIC_KEY}
      - BELEM_SUBSCRIBER_ID=${BELEM_SUBSCRIBER_ID}
      - BELEM_UNIQUE_KEY=${BELEM_UNIQUE_KEY}

  xplor_stg_nginx:
    logging:
      driver: "file-log-driver"
      options:
        fpath: "/docker/xplor_stg_nginx.log"
    image: nginx:alpine
    container_name: xplor-stg-nginx
    restart: always
    ports:
      - "1105:8080"
    depends_on:
      - onboarding_service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log:/etc/nginx/log/
      - ./api_json_errors.conf:/etc/nginx/api_json_errors.conf
    networks:
      - xplor-network

  # zookeeper:
  #   image: wurstmeister/zookeeper:latest
  #   ports:
  #     - "2182:2181"
  #   networks:
  #     - xplor-network
  # kafka:
  #   image: wurstmeister/kafka:2.11-1.1.1
  #   ports:
  #     - "9093:9092"
  #   restart: always
  #   links:
  #     - zookeeper
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: kafka
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  #     KAFKA_DELETE_TOPIC_ENABLE: "true"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.soc
  #   networks:
  #     - xplor-network

networks:
  xplor-network:
    external: true
